# Generated by Django 3.0.5 on 2020-05-09 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0002_auto_20200509_1202'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
