# Generated by Django 3.0.5 on 2020-05-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='percent',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
