# Generated by Django 3.0.5 on 2020-05-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0006_remove_profile_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='percent',
            field=models.CharField(blank=True, default='0', max_length=30),
        ),
    ]
