# Generated by Django 3.0.5 on 2020-05-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0007_profile_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='disrtict',
            new_name='district',
        ),
    ]
