# Generated by Django 3.0.5 on 2020-05-09 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0008_auto_20200509_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('temperature', models.FloatField()),
                ('cough', models.BooleanField()),
                ('headache', models.BooleanField()),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quaraDB.Profile')),
            ],
        ),
    ]
