# Generated by Django 3.0.5 on 2020-05-09 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0009_control'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('t', 'Temperature'), ('h', 'Headache'), ('th', 'Throatache'), ('o', 'Other')], default=0, max_length=50)),
                ('comment', models.TextField(blank=True, max_length=300)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quaraDB.Profile')),
            ],
        ),
    ]
