# Generated by Django 3.0.5 on 2020-05-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0010_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='urgently',
            field=models.BooleanField(default=True),
        ),
    ]
