# Generated by Django 3.0.5 on 2020-05-09 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0012_call_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_stat', models.CharField(max_length=30)),
                ('code', models.IntegerField(default=0)),
                ('cases', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
            ],
        ),
    ]
