# Generated by Django 3.0.5 on 2020-05-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0014_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
