# Generated by Django 3.0.5 on 2020-05-09 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quaraDB', '0015_shop_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='limit',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('expected', models.DateTimeField()),
                ('status', models.CharField(max_length=30)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quaraDB.Shop')),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quaraDB.Profile')),
            ],
        ),
    ]
